### ISSUE TITLE
Example uses uppercase @MaterializeInc/pulumi-docker-buildkit

### ISSUE THREAD

**Issue by badokun** [MaterializeInc/pulumi-docker-buildkit#14]
https://github.com/MaterializeInc/pulumi-docker-buildkit/blob/ebd49b7655ca8a7078d8123dafe303021e66f070/examples/aws-nodejs/index.ts#L2

Please update code to reflect @materializeinc/pulumi-docker-buildkit 

Was running into trouble with my circle-ci builds failing since it's running on Linux (case-sensitive), while I was developing on a Windows machine (case-insensitive)

**Comment by benesch** [comment]
Thanks! Sorry about that. Fixed now.
