### ISSUE TITLE
Feature Request: Manifest Support

### ISSUE THREAD

**Issue by tkram01** [MaterializeInc/pulumi-docker-buildkit#33]
It would be great if this package added support for manifests to handle pulling multi-arch images more easily.

https://aws.amazon.com/blogs/containers/introducing-multi-architecture-container-images-for-amazon-ecr/

**Comment by benesch** [comment]
Hey @tkram01! I'm afraid we've deprecated this provider, as v4.0 of the official pulumi-docker provider has ~all of the enhancements in this provider. Here's the announcement blog post: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/

If you're still interested in this feature, would recommend that you re-file against the official provider: https://github.com/pulumi/pulumi-docker
