### ISSUE TITLE
context digest computation is wrong

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/pulumi-docker-buildkit#5]
It needs to take into account the Dockerfile too. Or there needs to be a separate Dockerfile digest that it tracks.

**Comment by benesch** [comment]
Fixed in #7.

**Comment by antifuchs** [comment]
This is, sadly, yet unfixed: In `pulumi up`ing in the repro repo for #6 (https://github.com/antifuchs/repro-docker-buildkit-issue-6), I see the same one-file docker repo result in several different build contexts; but not ALL of them are different - maybe it's time-based?

**Comment by benesch** [comment]
Ah, shoot, I think I remember now. Docker's own build context hashing isn't deterministic, IIRC. I believe it's based on creating a tarball, and tar archives have timestamps in them, or something like that. That's why I wrote the computation myself. I think we need to revert #7 and just add the Dockerfile to the hash.

**Comment by antifuchs** [comment]
One idea I had was to do what you did with the dir traversal, but [read the tar stream](https://pkg.go.dev/archive/tar@go1.17.3) & hash that deterministically (just pathname, file mode & contents). I believe that should give us a stable hash, and still be less work than trying to build it ourselves.
