### ISSUE TITLE
Pushing to multiple new repos has a race condition

### ISSUE THREAD

**Issue by antifuchs** [MaterializeInc/pulumi-docker-buildkit#6]
When bringing up a new stack that contains two newly-created ECR repos, there's a race condition in the image-pushing code (in `docker buildx`, it seems, as that's where the error message is coming from?): We get the following error:

```
  docker-buildkit:index:Image (mzcloud-asf-[redacted]):
    Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.``
    error: docker login failed: exit status 1
```

I imagine this is a too-big critical section without a lock on docker's part, but maybe there is an easy way to shorten the critical section? (Push an "empty" image to a new ECR without building?)

**Comment by benesch** [comment]
We've not seen this in a very long time, AFAIK. Calling this resolved!
